# Generated by Django 6.0.5 on 2026-07-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0010_order_payment_status_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
